language: python
python: 3.5
install:
- pip install -r requirements-dev.txt
- python setup.py install
script: py.test
deploy:
  provider: pypi
  user: tonyfast
  password:
    secure: EMklg0H0ph40OXBxFoZD+mbpL5RaKVDBq2g1hUaFsDM0wFosWGh/iDtuGDG1p9SGYHmiynuxPA9HyiXgb/ewikl0SWpKtl8ADdwCCmrnndcXg/fzAmOn47GgzG15PxU8VeXjFrCamkbL32e+ZjiGglzefl4RIZ0whwbHd7h27ys2ZSx/H+DMq3bifWsMQF+eIW9pH18zQiqGJ9iOZnVXKveEo7zC12IjEmohMNnWdKCKkTMBC7rR45ROqTsfOn5SYaNSLFL60RpK1YcHE0SkvcGBdtFIcu5XiI7YPUFX7HwpouzKPgFMcjpioWKDgboeUwdS0f/6Wmvz2yAzqRMbFpSd6bBIdgxG3M/rTqw1T34W6mUQ0LX7IB7OviXEOqmA+XSPZbgwjLa1CKRh7IDWaMM0cPmjOHYBAuu6MOE/2E021IJlC9k+7OJM+a7FNYNav2N2c9HD7UgR6XX8R1utiJqBCquNqxbbHT0gJmjkihgSfGoVrOcTKsCSYXZtLc9F93WcxQLULO1Nen7vZE3LZOp6EGW3oTBYekQphyMYAhVlHiKJ0HorGm9w1tUgLgBAH70hmld+l3APepGzahRm7u6Ek6JZ/xq03wl1zqXe5HWifSqCJvSliCTylmkOuK3FoCu00FjMMDHUo1X25ssJAMAg2xG+eKgBmUyupF5J1CY=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: tonyfast/magical-magic
